### ISSUE TITLE
It is not clear what packages and features require Gambit

### ISSUE THREAD

**Issue by dleslie** [fourthbit/spheres#1]
Title says it all.

I'd love to collaborate on making the R7RS ecosystem healthier, and it seems Scheme Spheres is endeavouring in this direction, but it's not clear to what degree this project is still a Gambit-requiring project.

**Comment by alvatar** [comment]
Well, the intention is to place everything that is Gambit-specific in the gambit/ directory (spheres/gambit\* *). However, at the moment, for the sake of being pragmatical, many other modules use Gambit procedures. The intention is to make first a version with all libraries I'm considering for Spheres with Gambit support only. Then it could be ported to other systems as well. The project is organized with that in mind.
Some (but very few) libraries may never be portable to some Scheme implementations (such as Termite which requires powerful serialization support). It can be ported to Chicken for example.

So, if you want to contribute for another system, current code should be handled with (cond-expands), and the very implementation specific libraries should go to /{implementation} folder.

**Comment by dieggsy** [comment]
@alvatar is the API that would need to be implemented to port all this to an arbitrary scheme implementation defined somewhere? I can sorta get it by reading through the gambit directory

**Comment by alvatar** [comment]
I don't remember very well (it's been years since I touch this code), but have you checked in schemespheres.org ? There are docs there
