### ISSUE TITLE
check-arg macro doesn't get expanded when loaded from a loaded file from repl

### ISSUE THREAD

**Issue by snifel0** [fourthbit/spheres#19]
hi.

the check-arg macro is expanded properly when i load the list package like
;; repl

> (load (spheres/algorithm list))

but when i load a file from repl that loads the package like this;
;; file.scm
(load (spheres/algorithm list))

;; repl

> (load "file.scm")

the check-arg doesn't get expanded and remains unbound

**Comment by alvatar** [comment]
In this case I recommend you to use libraries for everything. Only that way you can make sure it has access to all its dependencies.
Alternatively you can just include the assert macros like this:

```
(include (spheres/core assert))
```
