### ISSUE TITLE
*** ERROR -- Can't open file "/usr/lib/gambit#.scm"

### ISSUE THREAD

**Issue by armontoubman** [fourthbit/spheres#2]
Hi,

After running spheres/gambit/scsc/compile.sh and copying and modifying .gambcini, gsi throws the following error on startup:

```
*** ERROR -- Can't open file "/usr/lib/gambit#.scm"
(##include "~~/lib/gambit#.scm")
```

I'm on Fedora Linux 21 (64-Bit) with Gambit 4.7.3. After some experiments I found that "~~/lib/" expands to the wrong path on my computer:

```
> (path-expand "~~/lib/")
"/usr/lib/"
> (path-expand "~~lib/")
"/usr/lib64/gambit-c/"
```

Removing the / from the include paths in `spheres/gambit/library.scm` and `spheres/gambit/ffi/ffi-dependent.scm` solved it for me, gsi now loads the spheres correctly.

**Comment by alvatar** [comment]
Fixed!
Thanks a lot for reporting it!
