### ISSUE TITLE
How can I compile into a portable executable?

### ISSUE THREAD

**Issue by snifel0** [fourthbit/spheres#20]
Hi

When I try to compile my script that uses some spheres packages through ssrun,
the executable calls the compiled spheres' object files.
If I try to run this executable on another computer,
it tries to locate the spheres' library path to load the object files
which doesn't exist!

So, to run this executable on another computer,
I am manually including the spheres' library sources into a big scheme source code..
Or should I copy the spheres libraries' object files into the same path of other computers?

Or... is there any other way, please? (because i am really using this project for my dailly chores)

**Comment by alvatar** [comment]
IRCC it is supported as an ssrun task. Looking at the ssrun/tasks/core.scm code will give you a lot of hints.
The problem here is the lack of documentation, but I don't have the time ATM to do it! I'll come back to it in the future.
