### ISSUE TITLE
local define

### ISSUE THREAD

**Issue by snifel0** [fourthbit/spheres#5]
hello. i want to make a bug report.

I think Gambit-C and Schemespheres expand one expression differently

(let () (define a 1) (define b (+ a 1)) b)
=> (letrec ((a 1) (b (+ a 1))) b)              (spheres)
=> (letrec\* ((a 1) (b (+ a 1))) b)             (gambit)

<Original Gambit-C>
C:>gsi -f
Gambit v4.7.7

> (let () (define a 1) (define b (+ a 1)) b)
> 2
> ,q

<SchemeSpheres>
C:>gsi
-- environment: debug -- preloaded libraries: (spheres/core meta) (spheres/core assert)
Gambit v4.7.7

> (let () (define a 1)  (define b (+ a 1)) b)
> **\* ERROR IN #<procedure #2>, (console)@1.33 -- (Argument 1) NUMBER expected
> (+ #!unbound 1)
> 1>

**Comment by alvatar** [comment]
Hi @snifel0 !
Thank you for the bug report. This behavior is really undefined, so you shouldn't rely on it AFAIK. I don't recall if its R5RS and R7RS. This is not an issue directly from Spheres, but from the Psyntax syntax expander. You can test this without Spheres, using the `-:s` flag, and you will see that you obtain the same behavior. 
Essentially, what Spheres really needs is a better syntax expander (Gambit needs that). But that's not the direct scope of Spheres, so is not a problem to fix at the moment. It will be very nice if that is done by Gambit, so we can keep building Spheres on top of it.

**Comment by snifel0** [comment]
Thank you for considering my issue. I really think your project is very useful!

It is not easy for me to accept that this behavior is undefined, since this form appears frequently in the famous book 'SICP' written by one of ceators of the languege scheme.

By the way, if this issue comes from the Psyntax expander, I should wait until a better expander for gambit comes up.

**Comment by alvatar** [comment]
Yes, the syntax expander has been an issue in Gambit since I first started using it, years ago. I wish I had the time to dive into this task! But is a complex and large task by itself...
