### ISSUE TITLE
unfold not exported in core/minimal

### ISSUE THREAD

**Issue by nortiero** [fourthbit/spheres#8]
Hi -- Great Work!

unfold procedure is not exported:  core/minimal.sld

Sorry to bother you with such a minor issue!

https://github.com/fourthbit/spheres/blob/master/spheres/core/minimal.sld

**Comment by alvatar** [comment]
Thank you @nortiero !
No issue is too minor if it makes sense! You are also welcome to do any pull request :)
Thanks again!
